from typing import Dict, List, Protocol, Set, Tuple, Any
from models import Profile, Location

class IProfileService(Protocol):
    """Interface for profile management service."""
    
    def get_profiles(self) -> Dict[str, Profile]: ...
    
    def add_profile(self, profile: Profile) -> None: ...
    
    def update_profile(self, profile_id: str, profile: Profile) -> None: ...
    
    def get_profile(self, profile_id: str) -> Profile: ...
    
    def get_all_profiles(self) -> List[Profile]: ...
    
    def bulk_add_profiles(self, profiles: List[Profile]) -> None: ...

class IGeoService(Protocol):
    """Interface for geospatial indexing service."""
    
    def get_geo_index(self): ...
    
    def index_profile(self, profile_id: str, location: Location) -> str: ...
    
    def remove_from_index(self, quadrant: str, profile_id: str) -> bool: ...
    
    def get_users_in_quadrant(self, quadrant: str) -> Set[str]: ...
    
    def get_adjacent_quadrants(self, geohash: str) -> List[str]: ...
    
    def get_profile_geohash(self, profile_id: str) -> str: ...
    
    @staticmethod
    def calculate_distance(loc1: Location, loc2: Location) -> float: ...

class IExclusionService(Protocol):
    """Interface for user exclusion management."""
    
    def get_exclusion_manager(self): ...
    
    def initialize_user(self, user_id: str) -> None: ...
    
    def add_exclusion(self, user_id: str, excluded_id: str, exclusion_type: str) -> None: ...
    
    def get_excluded_users(self, user_id: str) -> Set[str]: ...

class IMatchingService(Protocol):
    """Interface for match score calculation."""
    
    def get_score_calculator(self): ...
    
    def compute_match_score(self, user_id: str, other_id: str, gender_preference: str = None) -> float: ...
    
    def is_within_matching_distance(self, user_id: str, other_id: str) -> bool: ...

class IPrecomputeService(Protocol):
    """Interface for match score precomputation."""
    
    def get_match_store(self): ...
    
    def precompute_matches(self, user_id: str) -> None: ...
    
    def get_precomputed_matches(self, user_id: str, excluded_ids: Set[str]) -> List[Tuple[str, float]]: ...

class IMatchFinderService(Protocol):
    """Interface for match finding and filtering."""
    
    def get_matches(self, user_id: str, limit: int = 8, gender_preference: str = None) -> List[Tuple[str, float]]: ...
